import { expect, test } from '@playwright/test'

test.use({ browserName: 'chromium', launchOptions: { args: ['--disable-gpu'] } })

async function openHome(page, reducedMotion = 'no-preference') {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.emulateMedia({ reducedMotion })
  await page.route('**/api/auth/me', route => route.fulfill({ status: 401, json: { detail: 'Not signed in' } }))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'FIND YOUR VOICE.' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Explore Tamil learning' })).toBeVisible()
  expect(await page.title()).toContain('ASD')
  await expect(page.locator('vite-error-overlay')).toHaveCount(0)
  return errors
}

test('slideshow timer pauses on hover, focus, page visibility, and explicit pause', async ({ page }) => {
  await page.clock.install()
  const errors = await openHome(page)
  const carousel = page.getByRole('region', { name: 'Explore Tamil learning' })
  const slide = carousel.locator('[aria-roledescription="slide"]')
  await page.clock.pauseAt(new Date(Date.now() + 1000))
  // Reset the reading interval after loading; otherwise real navigation time
  // consumes part of the first eight seconds before the test starts counting.
  await carousel.dispatchEvent('mouseenter')
  await carousel.hover()
  await page.mouse.move(0, 0)
  await page.clock.runFor(7999)
  await expect(slide).toHaveAttribute('aria-label', /^1 of 3/)
  await page.clock.runFor(1)
  await expect(slide).toHaveAttribute('aria-label', /^2 of 3/)
  await carousel.hover()
  await page.clock.runFor(16000)
  await expect(slide).toHaveAttribute('aria-label', /^2 of 3/)
  await page.mouse.move(0, 0)
  await carousel.getByRole('button', { name: 'Next slide', exact: true }).focus()
  await page.clock.runFor(16000)
  await expect(slide).toHaveAttribute('aria-label', /^2 of 3/)
  await page.keyboard.press('ArrowRight')
  await expect(slide).toHaveAttribute('aria-label', /^3 of 3/)
  await page.keyboard.press('Home')
  await expect(slide).toHaveAttribute('aria-label', /^1 of 3/)
  await carousel.getByRole('button', { name: 'Pause slideshow' }).click()
  await page.getByRole('link', { name: 'Meet the vowels', exact: true }).focus()
  await page.mouse.move(0, 0)
  await page.clock.runFor(16000)
  await expect(slide).toHaveAttribute('aria-label', /^1 of 3/)
  await carousel.getByRole('button', { name: 'Play slideshow' }).click()
  await page.getByRole('link', { name: 'Meet the vowels', exact: true }).focus()
  await page.mouse.move(0, 0)
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange')) })
  await page.clock.runFor(16000)
  await expect(slide).toHaveAttribute('aria-label', /^1 of 3/)
  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: false }); document.dispatchEvent(new Event('visibilitychange')) })
  await page.clock.runFor(8000)
  await expect(slide).toHaveAttribute('aria-label', /^2 of 3/)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(carousel.getByRole('button', { name: 'Play slideshow' })).toBeVisible()
  await page.clock.runFor(16000)
  await expect(slide).toHaveAttribute('aria-label', /^2 of 3/)
  expect(errors).toEqual([])
})

test('reduced-motion homepage remains still and supports manual Tamil slide navigation', async ({ page }) => {
  await page.clock.install()
  const errors = await openHome(page, 'reduce')
  const carousel = page.getByRole('region', { name: 'Explore Tamil learning' })
  await expect(carousel.getByRole('button', { name: 'Play slideshow' })).toBeVisible()
  await page.clock.runFor(32000)
  await expect(carousel.locator('[aria-roledescription="slide"]')).toHaveAttribute('aria-label', /^1 of 3/)
  await carousel.getByRole('button', { name: 'Show slide 3: A small sentence. A new beginning.' }).click()
  await expect(carousel.getByText('அம்மா, வா.', { exact: true })).toBeVisible()
  await expect(carousel.getByRole('link')).toHaveAttribute('href', '/tamil?kind=sentence')
  expect(await carousel.locator('.home-slide-petal').first().evaluate(element => getComputedStyle(element).animationName)).toBe('none')
  expect(await carousel.locator('h2').evaluate(element => getComputedStyle(element).fontFamily)).toContain('Noto Sans Tamil')
  await carousel.getByRole('button', { name: 'Previous slide' }).click()
  await expect(carousel.getByRole('link')).toHaveAttribute('href', '/tamil?kind=word')
  expect(errors).toEqual([])
})

for (const width of [1440, 390]) test(`homepage slideshow is usable without overflow at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 })
  const errors = await openHome(page, 'reduce')
  const carousel = page.getByRole('region', { name: 'Explore Tamil learning' })
  await page.evaluate(() => document.fonts.ready)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `C:/final_year_project/.runlogs/home-slideshow-${width}-first.png` })
  for (let index = 1; index <= 3; index++) {
    await carousel.getByRole('button', { name: new RegExp(`Show slide ${index}:`) }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const bounds = await carousel.boundingBox()
    expect(bounds.x).toBeGreaterThanOrEqual(0)
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(width)
    for (const control of await carousel.getByRole('button').all()) expect((await control.boundingBox()).height).toBeGreaterThanOrEqual(44)
  }
  await page.locator('.voice-guide-band').scrollIntoViewIfNeeded()
  await expect(page.locator('.voice-guide-band img')).toHaveJSProperty('complete', true)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `C:/final_year_project/.runlogs/home-slideshow-${width}.png`, fullPage: true })
  expect(errors).toEqual([])
})
