import { Link } from 'react-router-dom'
import { ArrowRight, ArrowUpRight, Headphones, Mic2, BarChart3 as ChartNoAxesCombined, ShieldCheck, HeartHandshake } from 'lucide-react'
import VowelShell from '../components/layout/VowelShell'
import { VowelPairRail, VOWEL_GAMES } from './VowelPages'
import './LandingPage.css'
import './LandingPageAtmosphere.css'
import HomeSlideshow, { HOME_SLIDES } from '../features/home/HomeSlideshow'
import useHomeReveals from '../features/home/useHomeReveals'
import useHomeParallax from '../features/home/useHomeParallax'
import useHomeBackgroundParallax from '../features/home/useHomeBackgroundParallax'
import useComfortMotion from '../features/home/useComfortMotion'
import DemoEntry from '../features/home/DemoEntry'

export default function LandingPage() {
  const reduced = useComfortMotion()
  const hero = useHomeParallax(reduced)
  useHomeReveals(reduced)
  useHomeBackgroundParallax(reduced)
  return <VowelShell className={reduced ? 'voice-home voice-home-calm' : 'voice-home'}>
    <section ref={hero} className="voice-home-hero" aria-labelledby="voice-home-title" data-motion={reduced ? 'reduced' : 'full'} data-parallax-background="sky">
      <div className="voice-home-copy"><h1 id="voice-home-title"><span>FIND</span><br /><span>YOUR</span><br /><em>VOICE.</em></h1><p>Small sounds. Growing confidence.<br /><span lang="ta">தமிழ் உயிரெழுத்துகள், சொற்கள், வாக்கியங்கள்.</span><br className="voice-desktop-break" /> one gentle practice at a time.</p><div className="voice-hero-actions"><Link className="voice-button" to="/tamil">தமிழ் பயிற்சி <ArrowUpRight size={24} /></Link><a className="voice-text-link" href="#meet-the-vowels">Meet the vowels</a></div><nav className="voice-practice-chooser" aria-label="Choose Tamil practice"><span className="voice-practice-chooser__label">Choose your practice <ArrowRight size={16} aria-hidden="true" /></span><div className="voice-practice-chooser__links">{HOME_SLIDES.map((slide, index) => <Link key={slide.id} to={slide.to} className="voice-practice-chooser__link"><span className="voice-practice-chooser__number">0{index + 1}</span><strong>{slide.id}</strong><span lang="ta">{slide.sample}</span><ArrowUpRight size={16} aria-hidden="true" /></Link>)}</div></nav><DemoEntry /></div>
      <HomeSlideshow />
    </section>
    <div data-home-reveal className="voice-home-steps" id="how-it-works"><div><span>1</span><Headphones aria-hidden="true" /><p><strong>Listen closely</strong><small>Hear the vowel clearly.</small></p></div><div><span>2</span><Mic2 aria-hidden="true" /><p><strong>Record for 7 seconds</strong><small>Say one sound. We’re listening.</small></p></div><div><span>3</span><ChartNoAxesCombined aria-hidden="true" /><p><strong>See your progress</strong><small>Reflect and keep growing.</small></p></div></div>
    <section data-home-reveal data-parallax-background="forest" className="voice-home-how"><div><h2>Little moments.<br /><em>Meaningful practice.</em></h2><p>A clear prompt. A real recording. A helpful next step. Discover the sound you made and whether it was short or long, with Pippin beside you.</p><Link className="voice-button voice-button-lime" to="/practice">Let’s make a sound <ArrowRight size={20} /></Link></div><ol><li><span>01</span><div><h3>Find your sound</h3><p>Start with அ, ஆ, இ, ஈ… Learn all twelve Tamil vowels, then practise words and simple sentences.</p></div></li><li><span>02</span><div><h3>Make it your own</h3><p>Press Start and allow your microphone. Say the vowel once. Recording stops automatically after seven seconds.</p></div></li><li><span>03</span><div><h3>Take a small step forward</h3><p>See your detected vowel, its measured length, and helpful feedback. If the sound is unclear, simply try again.</p></div></li></ol></section>
    <section data-home-reveal data-parallax-background="ivory" className="voice-section" id="meet-the-vowels"><div className="voice-section-heading"><h2 lang="ta">தமிழ் உயிரெழுத்துகள்</h2><p>12 உயிரெழுத்துகள் · 5 குறில் · 7 நெடில். Begin with the five short/long pairs below; explore ஐ and ஔ in the complete alphabet.</p></div><VowelPairRail /><div className="voice-tamil-more"><Link to="/tamil/practice/letter-ai"><b lang="ta">ஐ</b><span>ஐகாரம் · ai</span></Link><Link to="/tamil/practice/letter-au"><b lang="ta">ஔ</b><span>ஔகாரம் · au</span></Link><p>ஐ, ஔ are நெடில் in Tamil grammar. These gliding vowels have individual phoneme practice.</p><Link className="voice-text-link" to="/tamil">12 உயிரெழுத்துகள் · சொற்கள் · வாக்கியங்கள் <ArrowRight size={18} /></Link></div><div className="voice-guide-band"><img src="/assets/vowel-studio/pippin-guide.png" alt="Pippin waves hello" loading="lazy" /><div><h2>Your voice has a friend.</h2><p>Pippin listens, celebrates, and helps you try again.</p></div><Link className="voice-button voice-button-lime" to="/play/pippin">Meet Pippin <ArrowRight size={20} /></Link></div></section>
    <section data-home-reveal data-parallax-background="ivory" className="voice-section voice-home-games"><div className="voice-section-heading"><h2>Practice, with<br /><em>a little more play.</em></h2><p>Catch a vowel. Build a tower. Follow Pippin. Find the way you love to learn.</p></div><div className="voice-home-game-list">{VOWEL_GAMES.map((game, index) => <Link key={game.id} to={'/games/vowels/' + game.id}><span>0{index + 1}</span><game.icon size={28} strokeWidth={1.4} /><h3>{game.title}</h3><p>{game.type}</p><ArrowUpRight size={22} /></Link>)}</div></section>
    <section data-home-reveal data-parallax-background="sky" className="voice-home-checkin"><div><span className="voice-checkin-orbit" aria-hidden="true"><Mic2 strokeWidth={1} /></span></div><div><h2>Every voice has<br /><em>its own journey.</em></h2><p>Try a ten-sound evaluation. See your strengths, discover sounds to revisit, and watch your own progress grow.</p><Link className="voice-button" to="/evaluate">Explore your progress <ArrowUpRight size={22} /></Link></div></section>
    <section data-home-reveal data-parallax-background="ivory" className="voice-home-care" id="research-privacy"><div><ShieldCheck size={25} /><h3>Your voice, thoughtfully handled.</h3><p>Your recording is processed by this application’s server. Vowel Studio saves measured results, not raw microphone recordings. You choose when to start.</p></div><div><HeartHandshake size={25} /><h3>A little support, together.</h3><p>Learning activities complement caregiver and clinician support. Your care workspace keeps the original guided lessons, reports, and account controls close by.</p><Link className="voice-text-link" to="/dashboard">Open care workspace <ArrowUpRight size={17} /></Link></div></section>
  </VowelShell>
}
